/**
 * Copyright (C) 2014-2015, Michiel Sikma <michiel@sikma.org>
 * MIT License
 *
 * src/data.js - invocation settings and main Pokémon data structure.
 */

/**
 * Namespace object of parsed command-line arguments, generated by the
 * argparse module, of which these are the defaults:
 *
 *   Namespace {
 *     path_icons: './resources/icons',
 *     path_data: './resources/pokedex.json',
 *     path_pngcrush: './pngcrush',
 *     tpl_js: './resources/pokesprite-tpl.js',
 *     tpl_scss: './resources/pokesprite-tpl.scss',
 *     output_img: './build/pokesprite.png',
 *     output_scss: './build/pokesprite.scss',
 *     output_js: './build/pokesprite.js',
 *     output_html: './build/overview.html',
 *     output_md: './build/overview.md',
 *     file_exts: 'png',
 *     icon_sets: '',
 *     generate_img: true,
 *     generate_scss: true,
 *     generate_js: true,
 *     generate_html: true,
 *     generate_md: false,
 *     lang: 'eng',
 *     padding: 1,
 *     exclude_pkmn: false,
 *     exclude_regular: false,
 *     exclude_shiny: false,
 *     exclude_forms: false,
 *     exclude_icon_sets: false,
 *     include_right: 1,
 *     skip_pngcrush: false,
 *     verbose: false }
 *
 * In reality, all paths will be absolute since they're resolved during
 * the parsing phase.
 *
 * @type {Namespace}
 */
export const settings = __ARGS__;

/**
 * Data from a JSON file, containing information on all Pokémon.
 * @type {Object}
 */
export const pokedex = require(settings['path_data']);
